title:            Oliver Eidel
description:      "Oliver Eidel's Blog"
url:              http://www.eidel.io
author:           Oliver Eidel
disqus_shortname: olieidel
google_analytics: UA-70715341-1
funny_quotes:
  - An App a Day keeps the Doctor at Play
  - Better a doctor working as a programmer than a programmer working as a doctor
  - "You can teach yourself to code you can't teach yourself medicine"

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Talks
    url:          /talks
  - name:         Publications
    url:          /publications
  - name:         Reading
    url:          /reading
  - name:         GitHub
    url:          http://github.com/olieidel
    external:     true
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
