title:            Oliver Eidel
# For some reason, jekyll-feed doesn't look at title but instead needs name
name:             Oliver Eidel
description:      "Oliver Eidel's Blog"
url:              https://www.eidel.io
author:           Oliver Eidel
google_analytics: UA-70715341-1
smartlook:        c9c5a6df7647642a0876dbf981a16ef0c8351236
funny_quotes:
  - An App a Day keeps the Doctor away.
  - Better a doctor working as a programmer than a programmer working as a doctor.
  - "You can teach yourself to code but you can't teach yourself medicine."
  - "A Quality Management System won't save you from writing crappy software."

permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-inline-svg
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-seo-tag

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - postcss.config.js
  - purgecss.config.js
  - README.md
  - yarn.lock
