title:            Eidel.io
description:      "Oliver Eidel's Blog"
footer:           An App a Day keeps the Doctor at Play
url:              http://www.eidel.io
author:           Oliver Eidel
disqus_shortname: olieidel
google_analytics: UA-70715341-1

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Talks
    url:          /talks
  - name:         Publications
    url:          /publications
  - name:         Reading
    url:          /reading
  - name:         GitHub
    url:          http://github.com/olieidel
    external:     true
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
