title:            Oliver Eidel
# For some reason, jekyll-feed doesn't look at title but instead needs name
name:             Oliver Eidel
description:      "Oliver Eidel's Blog"
url:              https://www.eidel.io
author:           Oliver Eidel
google_analytics: UA-70715341-1
funny_quotes:
  - An App a Day keeps the Doctor at Play
  - Better a doctor working as a programmer than a programmer working as a doctor.
  - "You can teach yourself to code but you can't teach yourself medicine."
  - "A Quality Management System won't save you from writing crappy software."

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Talks
    url:          /talks
  - name:         Publications
    url:          /publications
  - name:         Reading
    url:          /reading
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-inline-svg
