title:            'Oliver Eidel''s Blog'
description:      An App a Day keeps the Doctor away.
url:              http://www.eidel.io
signoff:          Oliver Eidel
disqus_shortname: olieidel
google_analytics: UA-70715341-1

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         Publications
    url:          /publications
  # - name:         Email
  #   url:          mailto:oli@eidel.net
  #   external:     true
  - name:         GitHub
    url:          http://github.com/olieidel
    external:     true
permalink:        pretty
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
